FROM dsuite/apk-builder:{{ALPINE_VERSION}}

LABEL maintainer="Hexosse <hexosse@gmail.com>" \
    org.opencontainers.image.title="docker-suite dsuite/apk-builder image" \
    org.opencontainers.image.description="Alpine package builder" \
    org.opencontainers.image.authors="Hexosse <hexosse@gmail.com>" \
    org.opencontainers.image.vendor="docker-suite" \
    org.opencontainers.image.licenses="MIT" \
    org.opencontainers.image.url="https://github.com/docker-suite/apk-builder" \
    org.opencontainers.image.source="https://github.com/docker-suite/apk-builder" \
    org.opencontainers.image.documentation="https://github.com/docker-suite/apk-builder/blob/master/Readme.md" \
    org.opencontainers.image.created="{{DOCKER_IMAGE_CREATED}}" \
    org.opencontainers.image.revision="{{DOCKER_IMAGE_REVISION}}"


## Install dev package commonly used
RUN \
	# Print executed commands
	set -x \
    # Update repository indexes
    && apk-update \
    # Install latest versions of packages included in alpine-sdk
    && apk-install \
        autoconf apache2-dev aspell-dev bash bison bzip2-dev curl-dev cyrus-sasl-dev \
        db-dev dbus-glib-dev freetds-dev file freetype-dev gd-dev gdbm-dev gettext-dev  \
        glib-dev gmp-dev icu-dev imap-dev krb5-dev libedit-dev libical-dev \
        libjpeg-turbo-dev libmcrypt-dev libmemcached-dev libpng-dev libressl-dev \
        libsodium-dev libtool libwebp-dev libxml2-dev libxpm-dev libxslt-dev \
        libzip-dev net-snmp-dev openldap-dev pcre-dev pcre2-dev postgresql-dev \
        re2c recode-dev samba-dev sqlite-dev tidyhtml-dev unixodbc-dev util-linux-dev \
        valgrind yaml-dev zlib-dev \
	# Clear apk's cache
	&& apk-cleanup
