FROM alpine:3.7

LABEL maintainer="Hexosse <hexosse@gmail.com>" \
      description="Alpine package builder." \
      vendor="docker-suite" \
      license="MIT"


ENV PACKAGER "Hexosse <hexosse@gmail.com>"


# Keys used to sign the packages
# To use your own keys, place it in /package/config folder
# and declare RSA_KEY_NAME
ENV RSA_KEY_NAME docker-suite.rsa
ENV PACKAGER_PRIVKEY /package/config/$RSA_KEY_NAME.priv
ENV PACKAGER_PUBKEY /package/config/$RSA_KEY_NAME.pub

#
ENV GIT_DISCOVERY_ACROSS_FILESYSTEM=1


## builder user
RUN \
	# Print executed commands
	set -x \
    # Create builder user member of group abuild
    && adduser -D -s /bin/ash -G abuild -g "Alpine Package Builder" builder \
    # Make our builder user like sudo
    && echo "builder ALL=(ALL) ALL" >> /etc/sudoers \
    && echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers


## Install
RUN \
	# Print executed commands
	set -x \
    # Update repository indexes
    && apk update --update-cache \
    # Install latest versions of packages included in alpine-sdk
    && apk add \
        # alpine-sdk
        alpine-sdk \
        # common tools
        cmake coreutils curl \
	# Clear apk's cache
	&& rm -rf /var/cache/apk/* /tmp/* /var/tmp/*


## Copy entrypoint script and make it executable
COPY --chown=builder:abuild /rootfs /
RUN \
	set -x \
    && chmod +x /usr/local/bin/generate-index.sh \
    && chmod +x /usr/local/bin/generate.sh \
    && chmod +x /entrypoint.sh


## Set default user to builder
USER builder


##
WORKDIR /package


## /package must contains the APKBUILD file
## /package/config must contains your public and private key
## /packages is where the apk files will be generated
VOLUME ["/package", "/packages"]


## Entrypoint
ENTRYPOINT ["/entrypoint.sh"]
