#!/bin/sh

# set -e : Exit the script if any statement returns a non-true return value.
set -e

# Make sure default folders exists
sudo mkdir -p /package
sudo mkdir -p /package/config
sudo mkdir -p /packages
[ -e /home/builder/.abuild ] || sudo ln -s /package/config/ /home/builder/.abuild

# Make them belong to user builder
sudo chown -R builder:abuild /package
sudo chown -R builder:abuild /packages

# Update repository indexes from all remote repositories
abuild-apk update 1&>/dev/null

# RSA private key
if [ ! -f "/package/config/$RSA_PRIVATE_KEY_NAME" ]; then

    # When using your own private key
    if [ "$RSA_PRIVATE_KEY" ]; then
        echo -e "$RSA_PRIVATE_KEY" > "/package/config/$RSA_PRIVATE_KEY_NAME"

    # Else, let generate one for you
    else
        if [ ! -f "$PACKAGER_PRIVKEY" ]; then
            echo "Generating private key \"${RSA_PRIVATE_KEY_NAME}\"..."
            openssl genrsa -out "/package/config/$RSA_PRIVATE_KEY_NAME" 2048
        fi
    fi

    # Generate public key if needed
    if [ ! -f "$PACKAGER_PUBKEY" ]; then
        echo "Generating public key \"${RSA_PRIVATE_KEY_NAME}.pub\" from private key \"${RSA_PRIVATE_KEY_NAME}\"..."
        openssl rsa -in "/package/config/$RSA_PRIVATE_KEY_NAME" -pubout -out "$PACKAGER_PUBKEY"
    fi

    # Install key
    sudo cp "$PACKAGER_PUBKEY" /etc/apk/keys/
fi

# abuild.conf file
if [ ! -f "/package/config/abuild.conf" ]; then
    # Generate abuild.conf file
    # Copy file from: https://github.com/alpinelinux/abuild/blob/master/abuild.conf
    curl "https://raw.githubusercontent.com/alpinelinux/abuild/master/abuild.conf" ${HTTP_PROXY:+ -x $HTTP_PROXY} -s -L --output "/package/config/abuild.conf"
    # Change REPODEST
    sed -i -e 's|REPODEST=$HOME/packages/|REPODEST=/packages/|' /package/config/abuild.conf
    # Uncomment MAINTAINER
    sed -i -e 's|#MAINTAINER="$PACKAGER"|MAINTAINER="$PACKAGER"|' /package/config/abuild.conf
    # Add PACKAGER_PRIVKEY
    echo >> /package/config/abuild.conf
    echo '# Path to your private key' >> /package/config/abuild.conf
    echo PACKAGER_PRIVKEY="\"/package/config/${RSA_PRIVATE_KEY_NAME}\"" >> /package/config/abuild.conf
fi

# Working directory
cd /package

# Just to remove anoying message
export GIT_DISCOVERY_ACROSS_FILESYSTEM=1

# Execute command
exec "$@"
